extensions:
  health_check: {}
receivers:
  otlp:
    protocols:
      grpc:
      http:
  filelog:
    include: [/etc/otelcol-contrib/app-logs/*.logs]
processors:
  resource:
    attributes:
      - key: "service"
        value: "nodeaApp"
        action: insert   
      - key: environment
        value: testing
        action: insert 
exporters:
  logging:
    logLevel: $LOG_EXPORTER_LOG_LEVEL
  otlp:
    endpoint: https://otlp.nr-data.net:4317
    headers:
      "api-key": $NEW_RELIC_LICENSE_KEY
service: 
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [resource]
      exporters: [logging, otlp]
    traces:
      receivers: [otlp]
      processors: [resource]
      exporters: [logging, otlp]
    logs:
      receivers: [filelog]
      processors: [resource]
      exporters: [logging, otlp]